[package]
name = "add-one"
version = "0.1.0"
authors = ["Jasper <jasperav@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.14"
difference = "1.0.0"